spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssafyspecial
#    url: jdbc:mysql://j5d205.p.ssafy.io:3306/ssafyspecial
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#       show_sql: true
#       format_sql: true

        
logging.level:
  org.hibernate.SQL: error
  
    

  
